### ISSUE TITLE
WinError 87 on Windows7

### ISSUE THREAD

**Issue by ghost** [Pylons/hupper#12]
Hi,

I have a problem starting a pyramid project with --reload on Windows7

When I type `hupper -m http.server` I get:
```
λ hupper -m http.server
Traceback (most recent call last):
  File "C:\Tools\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Tools\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Devel\pyramid\quick_tutorial\env\Scripts\hupper.exe\__main__.py", line 9, in <module>
  File "c:\devel\pyramid\quick_tutorial\env\lib\site-packages\hupper\cli.py", line 21, in main
    worker_kwargs={"alter_sys": True, "run_name": "__main__"})
  File "c:\devel\pyramid\quick_tutorial\env\lib\site-packages\hupper\reloader.py", line 290, in start_reloader
    return reloader.run()
  File "c:\devel\pyramid\quick_tutorial\env\lib\site-packages\hupper\reloader.py", line 111, in run
    if not self._run_worker():
  File "c:\devel\pyramid\quick_tutorial\env\lib\site-packages\hupper\reloader.py", line 144, in _run_worker
    self.worker.start()
  File "c:\devel\pyramid\quick_tutorial\env\lib\site-packages\hupper\worker.py", line 129, in start
    os.set_inheritable(self.stdin_fd, True)
OSError: [WinError 87] Falscher Parameter
```
I get the same error when starting the pyramid project with --reload

Do you have any idea what I am doing wrong?
Thanks you very much
Regards
Seyhbold

**Comment by mmerickel** [comment]
I'm sorry to hear you're having issues. Is there a chance you could edit the file to remove the `os.set_inheritable(self.stdin_fd, True)` call from the code temporarily and see if things work then?

**Comment by ghost** [comment]
I commented out lines 128 and 129 in worker.py.

```python
        # py34 and above sets CLOEXEC automatically on file descriptors
        # NOTE: this isn't usually an issue because multiprocessing doesn't
        # actually exec on linux/macos, but we're depending on the behavior
#        if hasattr(os, 'set_inheritable'):  # pragma: nocover
#            os.set_inheritable(self.stdin_fd, True)
```

With this result
```
λ hupper -m http.server
Traceback (most recent call last):
  File "C:\Tools\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Tools\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Devel\pyramid\quick_tutorial\env\Scripts\hupper.exe\__main__.py", line 9, in <module>
  File "c:\devel\pyramid\quick_tutorial\env\lib\site-packages\hupper\cli.py", line 21, in main
    worker_kwargs={"alter_sys": True, "run_name": "__main__"})
  File "c:\devel\pyramid\quick_tutorial\env\lib\site-packages\hupper\reloader.py", line 290, in start_reloader
    return reloader.run()
  File "c:\devel\pyramid\quick_tutorial\env\lib\site-packages\hupper\reloader.py", line 111, in run
    if not self._run_worker():
  File "c:\devel\pyramid\quick_tutorial\env\lib\site-packages\hupper\reloader.py", line 144, in _run_worker
    self.worker.start()
  File "c:\devel\pyramid\quick_tutorial\env\lib\site-packages\hupper\worker.py", line 149, in start
    send_fd(self.pipe, self.stdin_fd, self.pid)
  File "c:\devel\pyramid\quick_tutorial\env\lib\site-packages\hupper\ipc.py", line 35, in send_fd
    0, False, winapi.DUPLICATE_SAME_ACCESS,
  File "c:\devel\pyramid\quick_tutorial\env\lib\site-packages\hupper\winapi.py", line 123, in DuplicateHandle
    CheckError(ret, 'failed to duplicate handle')
  File "c:\devel\pyramid\quick_tutorial\env\lib\site-packages\hupper\winapi.py", line 112, in CheckError
    raise ctypes.WinError(ctypes.get_last_error(), msg)
OSError: [WinError 87] failed to duplicate handle
```

**Comment by mmerickel** [comment]
I did all of my testing on windows 10 and appveyor (windows 2012 r2). I have to think this is related to a difference there between those and windows 7. How frustrating. I will try to find a way to setup a windows 7 vm.

**Comment by kalbermattenm** [comment]
I ran into the same problem (https://github.com/Pylons/pyramid/issues/2925) and tried @mmerickel's solution, but the result was exactly the same as the one reported by @seyhbold.

**Comment by mmerickel** [comment]
I've installed windows 7 (64-bit) SP1 and have tried running hupper's test suite using python 2.7.13 (64 and 32 bit) and python 3.6.0 (64 and 32 bit) and have not encountered any issues as of yet.

Can anyone who can reproduce this issue give me any more information about their systems or dig any deeper into what might be happening? Possibly download hupper's source and run its test suite to see if it fails.

**Comment by kalbermattenm** [comment]
To reproduce the issue:

* I am using Windows 7 (64-bit) professional SP1 and Python 2.7.10 (32-bit).
* The whole thing is then installed in a virtualenv (15.0.3):

```
cd tmp
mkdir test
cd test
virtualenv .
scripts\pip install pyramid>=1.8
scripts\pip install cookiecutter
scripts\cookiecutter https://github.com/Pylons/pyramid-cookiecutter-alchemy

   project_name [Pyramid Scaffold]: test
   repo_name [scaffold]: test

cd test
..\scripts\pip install -e .
..\scripts\pserve.exe --reload development.ini

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python27\Lib\multiprocessing\forking.py", line 380, in main
    prepare(preparation_data)
  File "C:\Python27\Lib\multiprocessing\forking.py", line 488, in prepare
    assert main_name not in sys.modules, main_name
AssertionError: __main__
Traceback (most recent call last):
  File "C:\Python27\Lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python27\Lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\tmp\test\scripts\pserve.exe\__main__.py", line 9, in <module>
  File "c:\tmp\test\lib\site-packages\pyramid\scripts\pserve.py", line 40, in ma
in
    return command.run()
  File "c:\tmp\test\lib\site-packages\pyramid\scripts\pserve.py", line 205, in r
un
    verbose=self.args.verbose,
  File "c:\tmp\test\lib\site-packages\hupper\reloader.py", line 290, in start_re
loader
    return reloader.run()
  File "c:\tmp\test\lib\site-packages\hupper\reloader.py", line 111, in run
    if not self._run_worker():
  File "c:\tmp\test\lib\site-packages\hupper\reloader.py", line 144, in _run_wor
ker
    self.worker.start()
  File "c:\tmp\test\lib\site-packages\hupper\worker.py", line 149, in start
    send_fd(self.pipe, self.stdin_fd, self.pid)
  File "c:\tmp\test\lib\site-packages\hupper\ipc.py", line 35, in send_fd
    0, False, winapi.DUPLICATE_SAME_ACCESS,
  File "c:\tmp\test\lib\site-packages\hupper\winapi.py", line 123, in DuplicateH
andle
    CheckError(ret, 'failed to duplicate handle')
  File "c:\tmp\test\lib\site-packages\hupper\winapi.py", line 112, in CheckError

    raise ctypes.WinError(ctypes.get_last_error(), msg)
WindowsError: [Error 87] failed to duplicate handle
```

**Comment by ghost** [comment]
Hi,

I just checked out master and ran the tests. I am not sure if this really helps:

The system is:
Windows 7 Enterprise 64bit, 16G Ram, Core i5-3320M

To be sure not to have path issues I have set a minimal %PATH%:
`C:\Devel\pyramid\py36\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\`

It is a newly created venv with:
```
py -m venv py36
pip install --upgrade setuptools
pip install -e .[testing]
```


```
(py36) C:\Devel\pyramid\hupper
λ py.test
============================= test session starts =============================
platform win32 -- Python 3.6.0, pytest-3.0.6, py-1.4.32, pluggy-0.4.0
rootdir: C:\Devel\pyramid\hupper, inifile: setup.cfg
plugins: cov-2.4.0
collected 5 items

tests\test_it.py FF
tests\test_reloader.py ...

================================== FAILURES ===================================
____________________ test_myapp_reloads_when_touching_ini _____________________

testapp = <TestApp(Thread-1, started 6760)>

    def test_myapp_reloads_when_touching_ini(testapp):
        testapp.start('myapp', ['--reload'])
>       testapp.wait_for_response(interval=1)

tests\test_it.py:11:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests\util.py:76: in wait_for_response
    interval=interval,
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

path = 'C:\\Users\\weissl\\AppData\\Local\\Temp\\tmp8oupxzso', last_size = 0
timeout = 5, interval = 1

    def wait_for_change(path, last_size=0, timeout=5, interval=0.1):
        start = time.time()
        size = os.path.getsize(path)
        while size == last_size:
            duration = time.time() - start
            sleepfor = interval
            if timeout is not None:  # pragma: no cover
                if duration >= timeout:
                    raise RuntimeError(
>                       'timeout waiting for change to file=%s' % (path,))
E                   RuntimeError: timeout waiting for change to file=C:\Users\weissl\AppData\Local\Temp\tmp8oupxzso

tests\util.py:100: RuntimeError
-------------------------- Captured stderr teardown ---------------------------
-- test app failed --
name=myapp
args=['--reload']
code=1
-- stdout --
Killing server with PID 8472.

-- stderr --
Traceback (most recent call last):
  File "C:\Tools\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Tools\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Devel\pyramid\hupper\tests\myapp\__main__.py", line 4, in <module>
    sys.exit(main(sys.argv[1:]) or 0)
  File "C:\Devel\pyramid\hupper\tests\myapp\cli.py", line 43, in main
    hupper.start_reloader(__name__ + '.main', **kw)
  File "c:\devel\pyramid\hupper\src\hupper\reloader.py", line 290, in start_reloader
    return reloader.run()
  File "c:\devel\pyramid\hupper\src\hupper\reloader.py", line 111, in run
    if not self._run_worker():
  File "c:\devel\pyramid\hupper\src\hupper\reloader.py", line 148, in _run_worker
    self.group.add_child(self.worker.pid)
  File "c:\devel\pyramid\hupper\src\hupper\ipc.py", line 28, in add_child
    return winapi.AssignProcessToJobObject(self.h_job, hp)
  File "c:\devel\pyramid\hupper\src\hupper\winapi.py", line 154, in AssignProcessToJobObject
    CheckError(ret, 'failed to assign process to job object')
  File "c:\devel\pyramid\hupper\src\hupper\winapi.py", line 112, in CheckError
    raise ctypes.WinError(ctypes.get_last_error(), msg)
PermissionError: [WinError 5] failed to assign process to job object

___________________ test_myapp_reloads_when_touching_pyfile ___________________

testapp = <TestApp(Thread-4, started 7472)>

    def test_myapp_reloads_when_touching_pyfile(testapp):
        testapp.start('myapp', ['--reload'])
>       testapp.wait_for_response(interval=1)

tests\test_it.py:24:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests\util.py:76: in wait_for_response
    interval=interval,
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

path = 'C:\\Users\\weissl\\AppData\\Local\\Temp\\tmprkye9l2h', last_size = 0
timeout = 5, interval = 1

    def wait_for_change(path, last_size=0, timeout=5, interval=0.1):
        start = time.time()
        size = os.path.getsize(path)
        while size == last_size:
            duration = time.time() - start
            sleepfor = interval
            if timeout is not None:  # pragma: no cover
                if duration >= timeout:
                    raise RuntimeError(
>                       'timeout waiting for change to file=%s' % (path,))
E                   RuntimeError: timeout waiting for change to file=C:\Users\weissl\AppData\Local\Temp\tmprkye9l2h

tests\util.py:100: RuntimeError
-------------------------- Captured stderr teardown ---------------------------
-- test app failed --
name=myapp
args=['--reload']
code=1
-- stdout --
Killing server with PID 6240.

-- stderr --
Traceback (most recent call last):
  File "C:\Tools\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Tools\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Devel\pyramid\hupper\tests\myapp\__main__.py", line 4, in <module>
    sys.exit(main(sys.argv[1:]) or 0)
  File "C:\Devel\pyramid\hupper\tests\myapp\cli.py", line 43, in main
    hupper.start_reloader(__name__ + '.main', **kw)
  File "c:\devel\pyramid\hupper\src\hupper\reloader.py", line 290, in start_reloader
    return reloader.run()
  File "c:\devel\pyramid\hupper\src\hupper\reloader.py", line 111, in run
    if not self._run_worker():
  File "c:\devel\pyramid\hupper\src\hupper\reloader.py", line 148, in _run_worker
    self.group.add_child(self.worker.pid)
  File "c:\devel\pyramid\hupper\src\hupper\ipc.py", line 28, in add_child
    return winapi.AssignProcessToJobObject(self.h_job, hp)
  File "c:\devel\pyramid\hupper\src\hupper\winapi.py", line 154, in AssignProcessToJobObject
    CheckError(ret, 'failed to assign process to job object')
  File "c:\devel\pyramid\hupper\src\hupper\winapi.py", line 112, in CheckError
    raise ctypes.WinError(ctypes.get_last_error(), msg)
PermissionError: [WinError 5] failed to assign process to job object

===================== 2 failed, 3 passed in 10.35 seconds =====================```

**Comment by ptcgh** [comment]
windows7 in chinese, have encountered the same problem.  how to ?

**Comment by mmerickel** [comment]
Well, I'm able to finally reproduce the `os.set_inheritable` error on Window 7 (64-bit) with Python 3.6.0 (32-bit). I'm evaluating what to do about this now.

**Comment by digitalresistor** [comment]
Use Python 3.x 64 bit instead?

**Comment by ghost** [comment]
I did use python 3.6 64bit and ran into this.

But hopefully you'll find the bug in the 32bit Version and it gives us hints for fixing the 64bit version as well.

**Comment by mmerickel** [comment]
As a quick update, I spent a while on this and I managed to create a version that worked on Windows 7 but of course it broke things on Windows 10. The core issue is that the `DuplicateHandle` function is not working for an unknown reason but only on Windows 7.

**Comment by mmerickel** [comment]
Fixed via #16. Thanks for the reports and let me know if the fix isn't working for you.

**Comment by ghost** [comment]
Hi thanks, so much for your support.

After installing latest version it works for me.

Thank you very much

**Comment by oholimoli** [comment]
hi,

is this issue resolved?

I'm using pytest on Windows with python 3.7 and get the following output:
```
(testenv) D:\GitLab\testenv\tests>python -m pytest
Traceback (most recent call last):
  File "D:\Programme\WPy64-3740\python-3.7.4.amd64\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Programme\WPy64-3740\python-3.7.4.amd64\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\hofo\Envs\testenv\lib\site-packages\pytest.py", line 102, in <module>
    raise SystemExit(pytest.main())
  File "C:\Users\hofo\Envs\testenv\lib\site-packages\_pytest\config\__init__.py", line 55, in main
    config = _prepareconfig(args, plugins)
  File "C:\Users\hofo\Envs\testenv\lib\site-packages\_pytest\config\__init__.py", line 200, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "C:\Users\hofo\Envs\testenv\lib\site-packages\pluggy\hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "C:\Users\hofo\Envs\testenv\lib\site-packages\pluggy\manager.py", line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Users\hofo\Envs\testenv\lib\site-packages\pluggy\manager.py", line 81, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "C:\Users\hofo\Envs\testenv\lib\site-packages\pluggy\callers.py", line 203, in _multicall
    gen.send(outcome)
  File "C:\Users\hofo\Envs\testenv\lib\site-packages\_pytest\helpconfig.py", line 89, in pytest_cmdline_parse
    config = outcome.get_result()
  File "C:\Users\hofo\Envs\testenv\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "C:\Users\hofo\Envs\testenv\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\hofo\Envs\testenv\lib\site-packages\_pytest\config\__init__.py", line 661, in pytest_cmdline_parse
    self.parse(args)
  File "C:\Users\hofo\Envs\testenv\lib\site-packages\_pytest\config\__init__.py", line 869, in parse
    self._preparse(args, addopts=addopts)
  File "C:\Users\hofo\Envs\testenv\lib\site-packages\_pytest\config\__init__.py", line 825, in _preparse
    early_config=self, args=args, parser=self._parser
  File "C:\Users\hofo\Envs\testenv\lib\site-packages\pluggy\hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "C:\Users\hofo\Envs\testenv\lib\site-packages\pluggy\manager.py", line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Users\hofo\Envs\testenv\lib\site-packages\pluggy\manager.py", line 81, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "C:\Users\hofo\Envs\testenv\lib\site-packages\pluggy\callers.py", line 208, in _multicall
    return outcome.get_result()
  File "C:\Users\hofo\Envs\testenv\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "C:\Users\hofo\Envs\testenv\lib\site-packages\pluggy\callers.py", line 182, in _multicall
    next(gen)  # first yield
  File "C:\Users\hofo\Envs\testenv\lib\site-packages\_pytest\capture.py", line 42, in pytest_load_initial_conftests
    _py36_windowsconsoleio_workaround(sys.stdout)
  File "C:\Users\hofo\Envs\testenv\lib\site-packages\_pytest\capture.py", line 815, in _py36_windowsconsoleio_workaround
    sys.stdin = _reopen_stdio(sys.stdin, "rb")
  File "C:\Users\hofo\Envs\testenv\lib\site-packages\_pytest\capture.py", line 808, in _reopen_stdio
    open(os.dup(f.fileno()), mode, buffering),
OSError: [WinError 87] Falscher Parameter
```

**Comment by digitalresistor** [comment]
@oholimoli this is not the issue tracker for pytest. You will want to file a bug report with pytest for this error!
