### ISSUE TITLE
gevent support

### ISSUE THREAD

**Issue by miohtama** [Pylons/hupper#13]
gevent is an infamous Python library of doing all sorts of monkey patching within the stdlib to get async support for stdlib modules, basically rewriting `threading` et al. [See one of related issues and good explanation](https://github.com/zopefoundation/transaction/issues/21).

After upgrading Pyramid 1.7 ->  Pyramid 1.8 I cannot run `pserve` anymore, despite doing in `gevent` monkey patches as early as possible in the launch script:

    """Wrapper for pserve."""
    import sys
    from pkg_resources import load_entry_point

    try:
        import gevent.monkey
        gevent.monkey.patch_all()
    except ImportError:
        pass

    def main():
        sys.exit(
            load_entry_point('pyramid', 'console_scripts', 'pserve')()
        )

I get exception on the startup:

    Starting monitor for PID 49731.
    Exception in thread Thread-2:
    Traceback (most recent call last):
      File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
        self.run()
      File "/Users/mikko/code/x/venv/lib/python3.5/site-packages/hupper/worker.py", line 98, in run
        while self.pipe.recv_bytes():  # pragma: nocover
      File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/connection.py", line 216, in recv_bytes
        buf = self._recv_bytes(maxlength)
      File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
        buf = self._recv(4)
      File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/connection.py", line 379, in _recv
        chunk = read(handle, remaining)
    BlockingIOError: [Errno 35] Resource temporarily unavailable

I do not have a solution yet; I leave issue open here to raise some awareness and for further investigation if there are other gevent users out there.

**Comment by mmerickel** [comment]
How about if you run `env/bin/hupper -m pyramid.scripts.pserve development.ini` ?

**Comment by digitalresistor** [comment]
Seems to be a known issue with gevent and multiprocessing: http://stackoverflow.com/questions/8678307/gevent-monkeypatching-breaking-multiprocessing

**Comment by mmerickel** [comment]
This might have a chance of working using #23.

**Comment by mmerickel** [comment]
@miohtama I released 0.5 which no longer uses multiprocessing so maybe you can revisit if this is still an issue.
