### ISSUE TITLE
Error using watchdog 2.1.4

### ISSUE THREAD

**Issue by lelit** [Pylons/hupper#72]
While `hupper` 1.10.3 works great with `watchdog` 2.1.3, with recently released 2.1.4 I get the following traceback:
```
Traceback (most recent call last):
  File "/usr/local/bin/pserve", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/pyramid/scripts/pserve.py", line 34, in main
    return command.run()
  File "/usr/local/lib/python3.9/site-packages/pyramid/scripts/pserve.py", line 245, in run
    hupper.start_reloader(
  File "/usr/local/lib/python3.9/site-packages/hupper/reloader.py", line 489, in start_reloader
    return reloader.run()
  File "/usr/local/lib/python3.9/site-packages/hupper/reloader.py", line 138, in run
    with self._setup_runtime():
  File "/usr/local/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.9/site-packages/hupper/reloader.py", line 179, in _setup_runtime
    with self._start_monitor():
  File "/usr/local/lib/python3.9/contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.9/site-packages/hupper/reloader.py", line 209, in _start_monitor
    self.monitor.start()
  File "/usr/local/lib/python3.9/site-packages/hupper/reloader.py", line 56, in start
    self.monitor.start()
  File "/usr/local/lib/python3.9/site-packages/watchdog/observers/api.py", line 254, in start
    for emitter in self._emitters.copy():
AttributeError: 'WatchdogFileMonitor' object has no attribute '_emitters'
```

**Comment by mmerickel** [comment]
Interesting... a quick review of the changes don't have anything that sticks out to me so I'll have to find some time to try to repro it.

https://github.com/gorakhargosh/watchdog/compare/v2.1.3...v2.1.4

**Comment by lelit** [comment]
Right, I did the same before posting and didn't spot anything, sorry.

**Comment by BoboTiG** [comment]
Hello,

Sorry for the regression, I am working on a fix right now (https://github.com/gorakhargosh/watchdog/issues/830).

**Comment by BoboTiG** [comment]
[Watchdog 2.1.5](https://github.com/gorakhargosh/watchdog/releases/tag/v2.1.5) released with the fix :)

**Comment by lelit** [comment]
Thank you! Since I'm leaving for a short vacation, I won't be able to give feedback until September.

**Comment by digitalresistor** [comment]
@BoboTiG thanks for the quick fix :-)
