### ISSUE TITLE
use of signal library prevents hupper from working if not in main thread of execution

### ISSUE THREAD

**Issue by zarquon5** [Pylons/hupper#76]
I tried to use hupper on a process running inside a windows service.  In order to use the win32serviceutil framework, I have to run my process in a separate thread, so that the main thread can listen for service control messages.  

Unfortunately, hupper does not work in this configuration, complaining:
```
Traceback (most recent call last):
  File "AppSrvService.py", line 73, in run
    WaitressServer.main(self.waitress_args)  # blocking
  File "c:\ProgramData\conda\envs\myenv\lib\site-packages\webware\Scripts\WaitressServer.py", line 181, in main
    serve(args)
  File "c:\ProgramData\conda\envs\myenv\lib\site-packages\webware\Scripts\WaitressServer.py", line 44, in serve
    hupper.start_reloader(
  File "c:\ProgramData\conda\envs\myenv\lib\site-packages\hupper\reloader.py", line 489, in start_reloader
    return reloader.run()
  File "c:\ProgramData\conda\envs\myenv\lib\site-packages\hupper\reloader.py", line 138, in run
    with self._setup_runtime():
  File "c:\ProgramData\conda\envs\myenv\lib\contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "c:\ProgramData\conda\envs\myenv\lib\site-packages\hupper\reloader.py", line 180, in _setup_runtime
    with self._capture_signals():
  File "c:\ProgramData\conda\envs\myenv\lib\contextlib.py", line 117, in __enter__
    return next(self.gen)
  File "c:\ProgramData\conda\envs\myenv\lib\site-packages\hupper\reloader.py", line 239, in _capture_signals
    psig = signal.signal(signum, handler)
  File "c:\ProgramData\conda\envs\myenv\lib\signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread of the main interpreter
```
The [Python documentation](https://docs.python.org/3/library/signal.html) states:
> Python signal handlers are always executed in the main Python thread, even if the signal was received in another thread. This means  that signals can’t be used as a means of inter-thread communication. You can use the synchronization primitives from the threading module instead.

Would it be possible to make hupper use [threading module](https://docs.python.org/3/library/threading.html#module-threading) primitives instead of signals?

**Comment by mmerickel** [comment]
> Would it be possible to make hupper use [threading module](https://docs.python.org/3/library/threading.html#module-threading) primitives instead of signals?

The short answer is no, the signals are not used for inter-thread communication but rather to receive SIGINT/SIGHUP/SIGTERM from the operating system and there is no replacement for those other than for your app to tell hupper when to shutdown programmatically which is not a typical use-case at all.

I'd like to understand more about what your app is trying to do because invoking `hupper.start_reloader()` from basically anywhere except the main thread really doesn't make sense. Can you provide some more context around the goal of that? Hupper reloads the entire process, not just a chunk of code, which is why you want it to be as high-level as possible in your program and not buried in a thread... because it's behavior is not isolated to that thread.

**Comment by mmerickel** [comment]
The goal should actually be to run `hupper.start_reloader()` **before** invoking the win32serviceutil framework. Then hupper creates the listener, and forks the subprocess which then runs the framework on the main thread. That would be the correct solution to this problem and should work just fine.
